# 448
WITH OFS AS (
    SELECT PRODUCT_ID, SALES_AMOUNT, NULL AS USER_ID, SALES_DATE
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
    UNION ALL
    SELECT PRODUCT_ID, SALES_AMOUNT, USER_ID, SALES_DATE
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-03'
)

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM OFS
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID