-- 코드를 입력하세요
WITH RENTING AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (DATE_FORMAT(START_DATE, '%Y-%m-%d') BETWEEN '2022-11-01' AND '2022-11-30') OR (DATE_FORMAT(END_DATE, '%Y-%m-%d') BETWEEN '2022-11-01' AND '2022-11-30') OR (DATE_FORMAT(START_DATE, '%Y-%m-%d') < '2022-11-01' AND DATE_FORMAT(END_DATE, '%Y-%m-%d') > '2022-11-30')
    GROUP BY CAR_ID
), CP AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = "30일 이상" 
    GROUP BY CAR_TYPE
)

SELECT CAR_ID, CAR_TYPE, (ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
LEFT JOIN CP USING (CAR_TYPE)
WHERE CAR_TYPE IN ('세단', 'SUV') AND CAR_ID NOT IN (SELECT * FROM RENTING) AND ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC