-- 코드를 입력하세요
SELECT B.FOOD_TYPE, REST_ID, REST_NAME, B.FAVORITES
FROM REST_INFO AS B, 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS A
WHERE B.FAVORITES = A.FAVORITES AND B.FOOD_TYPE = A.FOOD_TYPE
ORDER BY B.FOOD_TYPE DESC

