-- 코드를 작성해주세요
WITH RANKED AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) RANKING
    FROM ECOLI_DATA 
)

SELECT E.ID, CASE RANKING WHEN 1 THEN 'CRITICAL' WHEN 2 THEN 'HIGH' WHEN 3 THEN 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
FROM ECOLI_DATA E
JOIN RANKED R USING(ID)
ORDER BY E.ID