SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI USING(ANIMAL_ID)
WHERE AI.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female') AND AO.SEX_UPON_OUTCOME IN ('Spayed Male', 'Neutered Male', 'Spayed Female','Neutered Female')
ORDER BY AO.ANIMAL_ID