WITH A AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16' AND '2022-10-16' <= DATE_FORMAT(END_DATE, '%Y-%m-%d')
    GROUP BY CAR_ID
)

SELECT C.CAR_ID, IF (EXISTS(SELECT * FROM A WHERE C.CAR_ID = A.CAR_ID), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
GROUP BY CAR_ID
ORDER BY CAR_ID DESC