-- 코드를 작성해주세요
WITH A AS (
    SELECT EMP_NO, EMP_NAME, POSITION, EMAIL
    FROM HR_EMPLOYEES 
    JOIN HR_DEPARTMENT USING(DEPT_ID)
    )

SELECT SUM(SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE
JOIN A USING(EMP_NO)
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1