-- 코드를 입력하세요
SELECT UB.TITLE AS TITLE, UB.BOARD_ID AS BOARD_ID, UR.REPLY_ID AS REPLY_ID, UR.WRITER_ID AS WRITER_ID, UR.CONTENTS AS CONTENTS, DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS UR
JOIN USED_GOODS_BOARD AS UB
ON UR.BOARD_ID = UB.BOARD_ID
WHERE DATE_FORMAT(UB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY UR.CREATED_DATE ASC, UB.TITLE ASC